# Generated by Django 5.1.4 on 2024-12-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
